#!/usr/bin/env python3
"""
Critic Agent (Sufficiency Gate) — Logged ItV + VerifyLocate (Scheme 3)

Unified System:
- All question types (MC, QA, TF) use the Identify-then-Verify (ItV) gap extraction mechanism.
- Extracts missing information and verifies its presence in the context.
- Fully migrated to Unified Local LLM Engine (no multi-SDK branching).

Patch notes (compat & stability):
- Do NOT unconditionally pass OpenAI-only `response_format` to the unified client.
  Structured output is now behind env flag: ENABLE_STRUCTURED_OUTPUT=1
- Never return empty string from `_call_unified_llm`; always return a safe JSON fallback.
"""

import os
import time
import logging
import traceback
import json
import re
from datetime import datetime
from typing import Tuple, List, Dict, Any, Optional

import numpy as np
from sentence_transformers import SentenceTransformer
from core.llm_engine import LocalLLMClient

# NLTK sentence splitter (English-friendly)
import nltk
try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    nltk.download("punkt", quiet=True)
from nltk.tokenize import sent_tokenize

from core.trace_logger import (
    make_item_id,
    write_text,
    write_jsonl,
    write_run_meta,
    get_run_dir,
)

import random

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")

_emb_model: Optional[SentenceTransformer] = None
_llm_client: Optional[LocalLLMClient] = None

CRITIC_CALLS_PER_AGENT = int(os.environ.get("CRITIC_CALLS_PER_AGENT", "3"))
CRITIC_LLM_TEMPERATURE = float(os.environ.get("CRITIC_OPENAI_TEMPERATURE", "0.3"))  # kept env var name for backward compatibility


# ----------------------------
# Model/client getters
# ----------------------------
def get_emb_model() -> SentenceTransformer:
    global _emb_model
    if _emb_model is None:
        logging.info("Loading local embedding model for consensus voting...")
        _emb_model = SentenceTransformer("all-MiniLM-L6-v2")
    return _emb_model


def get_llm_client() -> LocalLLMClient:
    global _llm_client
    if _llm_client is None:
        _llm_client = LocalLLMClient()
    return _llm_client


# ----------------------------
# Prompts
# ----------------------------
_CRITIC_FORMAT_RULES = (
    "You MUST output your answer strictly as a valid JSON object.\n"
    "CRITICAL: Do NOT write any introduction, conclusion, or explanation. "
    "Your very first character MUST be '{' and your very last character MUST be '}'.\n"
    "{\n"
    '  "sufficient": true,\n'
    '  "gap": "NONE"\n'
    "}\n"
    "OR\n"
    "{\n"
    '  "sufficient": false,\n'
    '  "gap": "<short missing fact phrase>"\n'
    "}\n"
    "CRITICAL RULES FOR GAP IDENTIFICATION:\n"
    "1. Formulate the 'gap' as a concise, DECLARATIVE phrase representing the missing concept (e.g., 'recommended non-pharmacological interventions'), NOT as a question.\n"
    "2. Focus on QUALITATIVE clinical principles and caregiving concepts. Do not mark a context as insufficient merely because it lacks precise quantitative data (e.g., exact percentages, rates) or strict dictionary definitions, UNLESS the statement explicitly tests a numerical fact.\n"
    "3. If the core principle in the context provides sufficient logical ground to evaluate the statement's validity, set sufficient to true.\n"
    "4. Do NOT solve the question or mention option letters (A, B, C, D, E)."
)

SYS_ID_MC = (
    "You judge whether a CONTEXT is sufficient to answer a multiple-choice question. Identify only whether the "
    "context is sufficient and, if not, the single most important missing fact needed to determine the correct "
    f"option. {_CRITIC_FORMAT_RULES}"
)

SYS_ID_TF = (
    "You judge whether a CONTEXT is sufficient to decide if a TRUE/FALSE statement is true or false. Identify only "
    "whether the context is sufficient and, if not, the single most important missing fact needed to decide. "
    f"{_CRITIC_FORMAT_RULES}"
)

SYS_ID_QA = (
    "You judge whether a CONTEXT is sufficient to answer an open-ended question completely and accurately. Identify "
    "only whether the context is sufficient and, if not, the single most important missing fact needed to answer. "
    f"{_CRITIC_FORMAT_RULES}"
)


# ----------------------------
# Helpers & Guardrails
# ----------------------------
def _is_empty(x: str) -> bool:
    return (x is None) or (not str(x).strip())


def _is_none_strict(x: str) -> bool:
    return str(x).strip().upper() == "NONE"


def _clean_and_validate_gap(raw_gap: str) -> str:
    """[GUARDRAIL]: Clean and validate the gap generated by the sub-model to prevent option letter pollution."""
    gap = str(raw_gap or "").strip().strip("`\"'")
    gap = re.sub(r"\s+", " ", gap)

    if not gap or gap.upper() == "NONE":
        return "NONE"

    # 1) If it contains option terminology or single option letters, invalidate it
    if re.search(r"(?i)\boption\b", gap) or re.fullmatch(r"[A-E]", gap):
        return "NONE"

    # 2) If it contains verbose explanatory fluff or is too long, truncate or downgrade
    if len(gap) > 100 or len(gap.split()) > 12:
        return "NONE"

    return gap


def _parse_critic_response(x: str) -> Dict[str, Any]:
    raw = str(x or "").strip()
    parsed: Dict[str, Any] = {
        "raw": raw,
        "sufficient": None,
        "gap": "",
        "normalized_gap": "",
        "used_structured": False,
    }
    if not raw:
        return parsed

    # 1) Try to parse as JSON first
    json_str = re.sub(r"```json|```", "", raw).strip()
    try:
        match = re.search(r"\{.*\}", json_str, re.DOTALL)
        if match:
            json_str = match.group(0)

        data = json.loads(json_str)
        if "sufficient" in data:
            parsed["sufficient"] = bool(data["sufficient"])
            raw_gap = str(data.get("gap", "NONE"))
            parsed["gap"] = _clean_and_validate_gap(raw_gap)
            parsed["used_structured"] = True

            if parsed["sufficient"] is True or parsed["gap"] == "NONE":
                parsed["normalized_gap"] = "NONE"
            else:
                parsed["normalized_gap"] = parsed["gap"]
            return parsed
    except Exception:
        pass

    # 2) Fallback to regex extraction
    sufficient_match = re.search(r"(?im)^\s*sufficient\s*:\s*(yes|no|true|false)\b", raw)
    gap_match = re.search(r"(?im)^\s*gap\s*:\s*(.+)$", raw)
    if sufficient_match:
        parsed["used_structured"] = True
        sufficient_token = sufficient_match.group(1).strip().upper()
        parsed["sufficient"] = sufficient_token in {"YES", "TRUE"}
    if gap_match:
        parsed["used_structured"] = True
        parsed["gap"] = _clean_and_validate_gap(gap_match.group(1).strip())

    if parsed["used_structured"]:
        if parsed["sufficient"] is True or parsed["gap"] == "NONE":
            parsed["normalized_gap"] = "NONE"
        else:
            parsed["normalized_gap"] = parsed["gap"]
        return parsed

    # 3) Heuristic fallback for smaller / instruction-tuned models that do not obey strict JSON
    lower_raw = raw.lower()
    if re.search(r"\b(not sufficient|insufficient)\b", lower_raw):
        parsed["sufficient"] = False
        parsed["used_structured"] = True
    elif re.search(r"\bsufficient\b", lower_raw):
        parsed["sufficient"] = True
        parsed["used_structured"] = True

    freeform_gap_patterns = [
        r"(?i)missing (?:fact|information|info)(?: needed)?(?: is|:)?\s*(.+)$",
        r"(?i)gap(?: is|:)?\s*(.+)$",
        r"(?i)needed (?:fact|information|info)(?: is|:)?\s*(.+)$",
        r"(?i)the context (?:is )?missing\s+(.+)$",
    ]
    for pattern in freeform_gap_patterns:
        match = re.search(pattern, raw)
        if not match:
            continue
        candidate_gap = _clean_and_validate_gap(match.group(1).strip())
        if candidate_gap and candidate_gap != "NONE":
            parsed["gap"] = candidate_gap
            parsed["used_structured"] = True
            break

    if parsed["used_structured"]:
        if parsed["sufficient"] is True or parsed["gap"] == "NONE":
            parsed["normalized_gap"] = "NONE"
        else:
            parsed["normalized_gap"] = parsed["gap"]
        return parsed

    upper = raw.upper()
    if upper == "NONE":
        parsed["normalized_gap"] = "NONE"
        return parsed

    return parsed


def _normalize_gap_text(x: str) -> str:
    t = str(x or "").strip().strip("`")
    if not t:
        return ""

    parsed = _parse_critic_response(x)
    if parsed.get("normalized_gap"):
        return str(parsed["normalized_gap"])

    cleaned = _clean_and_validate_gap(t)
    return cleaned


def _is_valid_gap(x: str) -> bool:
    t = _normalize_gap_text(x)
    if not t or t == "NONE":
        return False
    if len(t) < 3 or len(t) > 120:
        return False
    if len(t.split()) > 12:
        return False
    if t.endswith("..."):
        return False
    if "\n" in t:
        return False
    if re.search(r"(?i)\b(context|question|statement|answer|explanation)\s*:", t):
        return False
    if re.search(r"(?i)\b(true or false|option\s+[A-E]|assistant|system|user)\b", t):
        return False
    return True


def _extract_mc_options(question: str) -> Dict[str, str]:
    options: Dict[str, str] = {}
    for line in str(question or "").splitlines():
        m = re.match(r"\s*([A-E])\.\s*(.+?)\s*$", line)
        if m:
            options[m.group(1).upper()] = m.group(2).strip()
    return options


def _looks_like_direct_answer(x: str, q_type: str, question: str) -> bool:
    t = _normalize_gap_text(x)
    if not t:
        return False

    q_type_u = str(q_type or "").strip().upper()
    lower_t = t.lower().strip()

    if q_type_u == "TF":
        return lower_t in {"true", "false", "yes", "no", "answer true", "answer false", "answer yes", "answer no"}

    if q_type_u == "MC":
        if re.fullmatch(r"[A-E]", t):
            return True

        option_match = re.match(r"^([A-E])(?:[\).:\-]|\s)+(.*)$", t)
        options = _extract_mc_options(question)
        if option_match:
            letter = option_match.group(1).upper()
            remainder = option_match.group(2).strip().lower()
            if letter in options:
                option_text = options[letter].lower()
                if not remainder or remainder == option_text or option_text in remainder or remainder in option_text:
                    return True

        normalized_options = {v.lower() for v in _extract_mc_options(question).values() if v}
        if lower_t in normalized_options:
            return True

    return False


def _gap_is_negative(gap: str) -> bool:
    g = (gap or "").strip().lower()
    neg_markers = [
        "does not state", "doesn't state", "not stated", "not mentioned",
        "not explicitly", "isn't mentioned", "is not mentioned", "lacks",
        "lack of", "missing:", "context does not", "the context does not",
    ]
    return any(m in g for m in neg_markers)


# ----------------------------
# Model calls: Identify
# ----------------------------
_SAFE_JSON_FALLBACK = '{"sufficient": true, "gap": "NONE"}'


def _call_unified_llm(
    sys_prompt: str,
    user_prompt: str,
    temperature: float = 0.3,
    max_tokens: int = 40,
    model_override: Optional[str] = None,
) -> str:
    """Call the unified LLM.

    Compatibility:
    - Do not assume OpenAI structured outputs exist.
    - Only pass `response_format` when explicitly enabled by env.

    Stability:
    - Never return empty string.
    """
    try:
        c = get_llm_client()
        target_model = model_override or os.environ.get("GLOBAL_AGENT_MODEL", "gpt-4o")

        extra_kwargs: Dict[str, Any] = {}
        if os.environ.get("ENABLE_STRUCTURED_OUTPUT", "0") == "1":
            extra_kwargs["response_format"] = {"type": "json_object"}

        r = c.chat.completions.create(
            model=target_model,
            temperature=temperature,
            max_tokens=max_tokens,
            messages=[
                {"role": "system", "content": sys_prompt},
                {"role": "user", "content": user_prompt},
            ],
            **extra_kwargs,
        )
        text = (r.choices[0].message.content or "").strip()
        return text or _SAFE_JSON_FALLBACK
    except Exception as e:
        logging.warning(f"Critic LLM call failed: {e}")
        return _SAFE_JSON_FALLBACK


# ----------------------------
# VerifyLocate (Scheme 3) with LLM Veto
# ----------------------------
def _make_sentence_windows(context: str, window_sents: int = 2, max_spans: int = 120) -> List[str]:
    if not context:
        return []
    try:
        sents = sent_tokenize(context)
    except Exception:
        sents = [x.strip() for x in context.split("\n") if x.strip()]
    if not sents:
        return []
    w = max(1, int(window_sents))
    spans: List[str] = []
    for i in range(len(sents)):
        chunk = " ".join(sents[i: i + w]).strip()
        if chunk:
            spans.append(chunk)
        if len(spans) >= max_spans:
            break
    return spans


def _score_span(retriever, query: str, span: str) -> float:
    try:
        return float(retriever.score_text(query=query, text=span))
    except TypeError:
        return float(retriever.score_text(query, span))
    except Exception:
        return -1.0


def _verify_locate_with_reranker(
    retriever,
    gap: str,
    context: str,
    window_sents: int = 2,
    max_spans: int = 120,
    threshold: float = 0.45,
) -> Dict[str, Any]:
    spans = _make_sentence_windows(context, window_sents=window_sents, max_spans=max_spans)
    if not spans or retriever is None:
        return {
            "present": False,
            "best_score": None,
            "best_span": "",
            "threshold": threshold,
            "n_spans": len(spans),
            "window_sents": window_sents,
        }

    best_score = None
    best_span = ""

    for sp in spans:
        sc = _score_span(retriever, query=gap, span=sp)
        if best_score is None or sc > best_score:
            best_score = sc
            best_span = sp

    preliminary_present = (best_score is not None) and (best_score >= float(threshold))
    final_present = preliminary_present

    # [LLM Veto]
    target_model = os.environ.get("GLOBAL_AGENT_MODEL", "gpt-4o")
    if preliminary_present and best_span:
        prompt_verify = (
            f"Determine if the following text snippet explicitly provides the missing information described as: '{gap}'.\n"
            f"If the text is merely asking a similar question, acting as a section header, or does not contain the actual factual answer, reply NO.\n"
            f"Snippet: {best_span}\n"
            f"Does the snippet provide the information? Reply ONLY YES or NO."
        )
        llm_response = _call_unified_llm(
            "You are a strict text verification system.",
            prompt_verify,
            temperature=0.0,
            max_tokens=50,
            model_override=target_model,
        )
        if "NO" in llm_response.upper():
            logging.info(
                f"LLM Veto applied: Reranker score was {best_score:.3f} but LLM rejected the snippet (model={target_model})."
            )
            final_present = False

    return {
        "present": bool(final_present),
        "best_score": best_score,
        "best_span": best_span,
        "threshold": threshold,
        "n_spans": len(spans),
        "window_sents": window_sents,
        "verify_model": target_model,
    }


# ----------------------------
# Markdown formatter
# ----------------------------
def _format_itv_markdown(trace: Dict[str, Any]) -> str:
    lines = []
    lines.append("# Critic ItV Trace\n")
    for k in [
        "run_dir", "ts", "item_id", "question_id", "q_type", "calls_per_agent",
        "none_frac_strict", "empty_frac", "invalid_gap_frac",
        "consensus_gap", "consensus_gap_is_negative",
        "verify_mode", "verify_label", "verify_best_score", "verify_threshold",
        "final_is_sufficient", "final_missing_info"
    ]:
        if k in trace:
            lines.append(f"- {k}: `{trace.get(k)}`")
    lines.append("\n---\n")
    lines.append("## Question\n```text\n" + (trace.get("question") or "") + "\n```\n")
    lines.append("## Context (FULL)\n```text\n" + (trace.get("context") or "") + "\n```\n")
    lines.append("\n## Identify Votes\n")
    for v in trace.get("votes", []) or []:
        normalized = (v.get("normalized_text") or "").strip()
        suffix = f" => {normalized}" if normalized and normalized != (v.get("text") or "").strip() else ""
        lines.append(f"- Round {v.get('round')} | {v.get('agent')}: ({v.get('label')}) {v.get('text')}{suffix}")
    lines.append("\n## Consensus details\n```json\n" + str(trace.get("consensus_debug", {})) + "\n```\n")

    if trace.get("verify_mode") == "locate_reranker":
        lines.append("\n## VerifyLocate (gap)\n")
        lines.append(f"- Label: **{trace.get('verify_label','')}**")
        lines.append(f"- Best score: `{trace.get('verify_best_score')}` (threshold `{trace.get('verify_threshold')}`)")
        lines.append("\n```text\n" + (trace.get("verify_best_span") or "") + "\n```\n")

    return "\n".join(lines)


# ----------------------------
# Main entry
# ----------------------------
def evaluate_sufficiency(
    question: str,
    context: str,
    q_type: str = "MC",
    calls_per_agent: int = CRITIC_CALLS_PER_AGENT,
    question_id: str = None,
    retriever=None,
    verify_threshold: float = 0.35,
    verify_window_sents: int = 2,
    verify_max_spans: int = 120,
) -> Tuple[bool, str, Dict[str, Any]]:
    ts = datetime.now().isoformat(timespec="seconds")
    run_dir = get_run_dir()
    item_id = make_item_id(question_id, question)

    trace: Dict[str, Any] = {
        "ts": ts,
        "run_dir": run_dir,
        "item_id": item_id,
        "question_id": question_id or item_id,
        "q_type": (q_type or "QA").strip().upper(),
        "calls_per_agent": calls_per_agent,
        "question": question,
        "context": context,
        "votes": [],
        "none_frac_strict": None,
        "empty_frac": None,
        "invalid_gap_frac": None,
        "valid_gaps": [],
        "invalid_gaps": [],
        "consensus_gap": "",
        "consensus_gap_is_negative": False,
        "verify_mode": "",
        "verify_label": "",
        "verify_best_score": None,
        "verify_threshold": None,
        "verify_best_span": "",
        "verify_n_spans": None,
        "verify_window_sents": None,
        "final_is_sufficient": None,
        "final_missing_info": "",
        "md_path": "",
        "consensus_debug": {},
    }

    # Identify
    q_type_u = (q_type or "QA").strip().upper()
    if q_type_u == "TF":
        sys_prompt = SYS_ID_TF
    elif q_type_u == "MC":
        sys_prompt = SYS_ID_MC
    else:
        sys_prompt = SYS_ID_QA

    votes = []
    empty_count = 0
    none_strict_count = 0
    invalid_gap_count = 0

    for i in range(int(calls_per_agent)):
        user_prompt = (
            f"Question/Statement:\n{question}\n\n"
            f"Context:\n{context}\n\n"
            "Return your JSON now:"
        )

        t0 = time.time()
        text = _call_unified_llm(
            sys_prompt,
            user_prompt,
            temperature=float(CRITIC_LLM_TEMPERATURE),
            max_tokens=80,
        )
        dt = time.time() - t0

        parsed = _parse_critic_response(text)
        normalized = parsed.get("normalized_gap") or ""

        if _is_empty(text):
            empty_count += 1
        if _is_none_strict(normalized):
            none_strict_count += 1
        if normalized and normalized != "NONE" and (not _is_valid_gap(normalized) or _looks_like_direct_answer(normalized, q_type_u, question)):
            invalid_gap_count += 1

        votes.append(
            {
                "round": i + 1,
                "agent": "critic",
                "latency_s": dt,
                "text": (text or "").strip(),
                "normalized_text": normalized,
                "label": "SUFFICIENT" if parsed.get("sufficient") else "INSUFFICIENT",
            }
        )

    trace["votes"] = votes
    trace["empty_frac"] = empty_count / max(1, int(calls_per_agent))
    trace["none_frac_strict"] = none_strict_count / max(1, int(calls_per_agent))
    trace["invalid_gap_frac"] = invalid_gap_count / max(1, int(calls_per_agent))

    # Consensus
    valid_gaps = []
    invalid_gaps = []
    for v in votes:
        ng = (v.get("normalized_text") or "").strip()
        if not ng or ng == "NONE":
            continue
        if _is_valid_gap(ng) and not _looks_like_direct_answer(ng, q_type_u, question):
            valid_gaps.append(ng)
        else:
            invalid_gaps.append(ng)

    trace["valid_gaps"] = valid_gaps
    trace["invalid_gaps"] = invalid_gaps

    consensus_gap = valid_gaps[0] if valid_gaps else "NONE"
    trace["consensus_gap"] = consensus_gap
    trace["consensus_gap_is_negative"] = _gap_is_negative(consensus_gap)

    any_sufficient = any(v.get("label") == "SUFFICIENT" for v in votes)

    # VerifyLocate
    verify = None
    if consensus_gap != "NONE" and retriever is not None and context:
        trace["verify_mode"] = "locate_reranker"
        verify = _verify_locate_with_reranker(
            retriever=retriever,
            gap=consensus_gap,
            context=context,
            window_sents=int(verify_window_sents),
            max_spans=int(verify_max_spans),
            threshold=float(verify_threshold),
        )
        present = bool(verify.get("present"))
        trace["verify_best_score"] = verify.get("best_score")
        trace["verify_threshold"] = verify.get("threshold")
        trace["verify_best_span"] = verify.get("best_span")
        trace["verify_n_spans"] = verify.get("n_spans")
        trace["verify_window_sents"] = verify.get("window_sents")
        trace["verify_label"] = "PRESENT" if present else "ABSENT"

        final_is_sufficient = present or any_sufficient
    else:
        trace["verify_mode"] = "none"
        trace["verify_label"] = ""
        final_is_sufficient = any_sufficient or (consensus_gap == "NONE")

    missing_info = "" if final_is_sufficient else consensus_gap

    trace["final_is_sufficient"] = bool(final_is_sufficient)
    trace["final_missing_info"] = missing_info

    # Write markdown trace (best-effort)
    try:
        md = _format_itv_markdown(trace)
        md_path = write_text("critic", f"critic_{trace['item_id']}.md", md)
        trace["md_path"] = md_path
    except Exception:
        pass

    # Write jsonl (best-effort)
    try:
        write_jsonl(
            "critic",
            "critic_traces.jsonl",
            {"trace": trace},
        )
    except Exception:
        pass

    return bool(final_is_sufficient), (missing_info or "").strip(), trace
